import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Sparkles, Check, Loader2 } from 'lucide-react';
import { EASE, DURATION } from '../../lib/motion';

/**
 * The waiting state for model-backed work.
 *
 * Forecasting, segmentation and retraining run on the Python service and can
 * take real seconds. A bare spinner makes that feel broken, so this names the
 * actual pipeline the request runs through.
 *
 * Deliberately honest: the backend streams no progress, so nothing here claims
 * a percentage or a completed step. Steps advance on a timer purely to show
 * *what the request is doing*, and the last one holds until the response lands.
 */

export function AIThinking({
  title = 'Running the model',
  steps = ['Contacting the model service', 'Running the 5-day ensemble', 'Scoring confidence'],
  className = '',
  compact = false,
}) {
  const [activeStep, setActiveStep] = useState(0);

  useEffect(() => {
    setActiveStep(0);
    const timer = setInterval(() => {
      // Hold on the final step rather than looping — looping would imply the
      // work restarted.
      setActiveStep((current) => (current < steps.length - 1 ? current + 1 : current));
    }, 1400);
    return () => clearInterval(timer);
  }, [steps.length]);

  if (compact) {
    return (
      <div className={`flex items-center gap-2.5 text-[13px] text-ink-muted ${className}`} role="status">
        <NeuralPulse size={16} />
        <motion.span key={activeStep} initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }}>
          {steps[activeStep]}…
        </motion.span>
      </div>
    );
  }

  return (
    <div
      className={`flex flex-col items-center justify-center rounded-xl border border-honey/18 bg-honey/5 px-6 py-9 ${className}`}
      role="status"
      aria-live="polite"
    >
      <NeuralPulse size={34} />

      <p className="mt-4 text-[14px] font-semibold text-ink">{title}</p>

      <ul className="mt-4 w-full max-w-xs space-y-2">
        {steps.map((step, index) => {
          const done = index < activeStep;
          const current = index === activeStep;
          return (
            <motion.li
              key={step}
              initial={{ opacity: 0, x: -6 }}
              animate={{ opacity: current || done ? 1 : 0.42, x: 0 }}
              transition={{ duration: DURATION.fast, ease: EASE }}
              className="flex items-center gap-2.5 text-[12.5px]"
            >
              <span className="flex h-4 w-4 shrink-0 items-center justify-center">
                {done ? (
                  <Check size={12} className="text-good" aria-hidden="true" />
                ) : current ? (
                  <Loader2 size={12} className="animate-spin text-honey" aria-hidden="true" />
                ) : (
                  <span className="h-1.5 w-1.5 rounded-full bg-ink-faint/50" aria-hidden="true" />
                )}
              </span>
              <span className={done ? 'text-ink-muted' : current ? 'text-ink' : 'text-ink-faint'}>{step}</span>
            </motion.li>
          );
        })}
      </ul>
    </div>
  );
}

/** Concentric rings that expand and fade — reads as "computing", not "stuck". */
export function NeuralPulse({ size = 28 }) {
  return (
    <span className="relative inline-flex items-center justify-center" style={{ width: size, height: size }}>
      <span className="absolute inset-0 animate-pulse-ring rounded-full bg-honey/25" aria-hidden="true" />
      <span
        className="absolute inset-0 animate-pulse-ring rounded-full bg-honey/20"
        style={{ animationDelay: '0.6s' }}
        aria-hidden="true"
      />
      <Sparkles size={size * 0.55} className="relative text-honey" aria-hidden="true" />
    </span>
  );
}

/** Inline "this value came from the model" marker. */
export function AIBadge({ label = 'AI', className = '' }) {
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-full border border-honey/25 bg-honey/10 px-1.5 py-0.5 text-[10px] font-semibold tracking-wide text-honey ${className}`}
      title="Generated by the SmartSales model service"
    >
      <Sparkles size={9} aria-hidden="true" />
      {label}
    </span>
  );
}

/** Indeterminate progress bar for long uploads / retrains. */
export function IndeterminateBar({ className = '' }) {
  return (
    <div className={`h-1 w-full overflow-hidden rounded-full bg-hairline/10 ${className}`} aria-hidden="true">
      <div
        className="h-full w-1/3 animate-sweep rounded-full"
        style={{
          background:
            'linear-gradient(90deg, transparent, rgb(var(--honey)), transparent)',
          backgroundSize: '200% 100%',
        }}
      />
    </div>
  );
}

export default AIThinking;
